In [1]:
import numpy as np


In [4]:
np.__version__

'1.16.2'

In [3]:
np.version

<module 'numpy.version' from 'C:\\Users\\Nandan\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [6]:
one_d=np.array([1,2,3,3,5]);

In [7]:
one_d

array([1, 2, 3, 3, 5])

In [10]:
import numpy as np

x = int(input("size of array :  " ))

arr =[]
for i in range(x):
    y = input()
    arr.append(y)

df=np.array(arr)
print(df)

size of array :  2
5
6
['5' '6']


In [15]:
my_array = np.array([])
a=int(input("Size of array:"))
for i in range(a):
    x=float(input("Element:"))
    my_array.append(x)

print(np.floor(my_array))

Size of array:5
Element:5


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [16]:
df=np.full((3,3),True,dtype=bool)

In [17]:
df

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [22]:
#. Extract all odd numbers from arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in arr:
    if arr[i]%2!=0:
        print(arr[i])

1
3
5
7
9


In [26]:
print(arr[arr % 2 != 0])
print(arr)


[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]


5. How to replace items that satisfy a condition with another value in numpy array?
Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

In [31]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[arr %2 !=0]=-1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6. How to replace items that satisfy a condition without affecting the original array?
Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

In [47]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out= np.where(arr %2 !=0,-1,arr);
print(out)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


7. How to reshape an array?
Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

In [56]:
arr=np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to stack two arrays vertically?
Difficulty Level: L2

Q. Stack arrays a and b vertically

In [77]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(11, 10).reshape(2,-1)

In [73]:
np.concatenate([a,b],axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

10. How to generate custom sequences in numpy without hardcoding?

In [83]:
a = np.array([1,2,3])
np.multiply(a,a)

array([1, 4, 9])

In [86]:
np.repeat(a, 3),np.tile(a,3)


(array([1, 1, 1, 2, 2, 2, 3, 3, 3]), array([1, 2, 3, 1, 2, 3, 1, 2, 3]))