# Accessing/changing Specific elements, rows, columns, etc

In [1]:
import numpy as np

In [3]:
a=np.array([[1,4,5,7,8],[6,8,4,9,7]])
print(a)

[[1 4 5 7 8]
 [6 8 4 9 7]]


In [4]:
#get specific element 
a[1,3]

9

In [6]:
#Get specific Row
a[0,:]

array([1, 4, 5, 7, 8])

In [7]:
#get specific col
a[:,3]

array([7, 9])

In [12]:
#getting a little more fancy [StartIndex:endindex:stepsize]
a[0,0:5:2]
#Dusra element print karega, Doo choor ke nahi


array([1, 5, 8])

In [15]:
a[1,4]=10
print(a)

[[ 1  4  5  7  8]
 [ 6  8  4  9 10]]


In [ ]:
#3d Example

In [17]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]);
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
#Get specific element (get outside in)
#[3d dimesion,row,column]

b[0,1,1]

4

In [20]:
#Other things will be same as 2d

## Initializing Different types of array

In [26]:
#All to 0's
np.zeros((4,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [27]:
#All to 1's
np.ones((4,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [28]:
# Any other number
np.full((2,2),99) #dimension, then initializing number

array([[99, 99],
       [99, 99]])

In [29]:
#Full_like allows us to built array of same size
np.full_like(a,4)
np.full(a.shape,4) #Another way

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

## random number initilization

In [31]:
# Random decimal numbers
np.random.rand(2,3)   #instead of [passing tuple we pass int dimension]

array([[0.05235179, 0.77351334, 0.98275501],
       [0.14258735, 0.33167501, 0.27479633]])

In [ ]:
# Random using shape of other array
np.random.random_sample(a.shape)

In [39]:
a.shape #Dimension n*n

(2, 5)

In [42]:
a.ndim #Dimension count

2

In [37]:
a.size

10

In [44]:
#Ramdom integer values
np.random.randint(4,8,size=(3,3)) #random number from 4-8

array([[6, 5, 5],
       [5, 6, 4],
       [5, 4, 5]])

## The identity Matrix

In [45]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
#Repeat an array
arr = np.array([[1,2,3],[4,5,6]])
r1 = np.repeat(arr,3,axis=1)
print(r1)
print(arr)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]
[[1 2 3]
 [4 5 6]]


numpy.repeat(a, repeats, axis=None)[source]
Repeat elements of an array.

Parameters:	
a : array_like
Input array.

repeats : int or array of ints
The number of repetitions for each element. repeats is broadcasted to fit the shape of the given axis.

axis : int, optional
The axis along which to repeat values. By default, use the flattened input array, and return a flat output array.

## Ex-1 Initilize a array

In [78]:
arr2 = np.ones((5,5));
print(arr2)

z = np.zeros((3,3))
z[1,1] =9
print(z)

arr2[1:-1,1:-1]= z
print(arr2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Copying array- Be careful

In [80]:
a = np.array([1,2,3])
b = a                     #DONT USE LIKE THIS, B BECOMES POINTER TO a
b[1]=100
print(a,b)

[  1 100   3] [  1 100   3]


In [82]:
a = np.array([1,2,3])
b = a.copy()                     # USE LIKE THIS
b[1]=100
print(a,b)

[1 2 3] [  1 100   3]
