# Mathematics

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a+2

array([3, 4, 5, 6])

In [5]:
a-2

array([-1,  0,  1,  2])

In [6]:
a*2

array([2, 4, 6, 8])

In [7]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [8]:
b = np.array([2,4,5,7])
a + b

array([ 3,  6,  8, 11])

In [9]:
a-b

array([-1, -2, -2, -3])

In [10]:
a*b


array([ 2,  8, 15, 28])

In [11]:
a ** 2


array([ 1,  4,  9, 16], dtype=int32)

#### take Sin and Cos

In [12]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [13]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [14]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)


In [16]:
x = np.ones((2,3));
print(x)
y = np.full((3,2),9)
print(y)
print(np.matmul(x,y))

[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9]
 [9 9]
 [9 9]]
[[27. 27.]
 [27. 27.]]


## Linear alzebra

In [18]:
# Find the determinant
c = np.identity(5)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

## Statistics

In [35]:
stats = np.array([[3,6,6]
                 ,[4,5,1]]);

In [41]:
np.min(stats, axis=1)

array([3, 1])

In [38]:
np.max(stats)

6

In [39]:
np.sum(stats)

25

## Reorgnanizing Array 

In [54]:
before = np.array([[2,5,6]
                   ,[5,6,7]])
print(before)

after = before.reshape(3,2)
print(after)

[[2 5 6]
 [5 6 7]]
[[2 5]
 [6 5]
 [6 7]]


In [58]:
# Vertically stacking array
v1 = np.array([3,6,8])
v2 = np.array([6,9,0])

np.vstack((v1,v2))

array([[3, 6, 8],
       [6, 9, 0]])

In [60]:
np.hstack((v1,v2))

array([3, 6, 8, 6, 9, 0])