# Miscellaneous

### Load Data from file

In [2]:
import numpy as np

In [7]:
filed = np.genfromtxt('test.txt', delimiter=",")
filed = filed.astype('int32') #Convert to different data type
filed


array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### Boolean Masking and Adveance indexing

In [9]:
#Returns array with true at the place condition matches
filed > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [11]:
#Get values greater than 50
filed[filed>50]  #Jo jo true h list me o return kiya h


array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [19]:
#You can index in list using List in NUMpy: Iterate list using lista = np.array([1,2,3,4,5,6,7])
a[[1,5,3]]

array([2, 6, 4])

In [22]:
#If any values in coulumns is greater than 50
np.any(filed>50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [23]:
##If any values in Rows is greater than 50
np.any(filed>50, axis=1)

array([ True,  True,  True])

In [25]:
#All values are greater than 50, columns wise
np.all(filed>50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [27]:
#In Between
(~((filed > 50) & (filed < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [28]:
filed[1:3,0:2]

array([[ 3, 42],
       [ 1, 22]])

In [30]:
filed

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [35]:
filed[[0,1,2],[1,2,3]]

array([13, 12, 11])

In [38]:
filed[[0,2], 3:]

array([[ 11, 196,  75,   4,   3,  34,   6,   7,   8,   0,   1,   2,   3,
          4,   5],
       [ 11, 999,  11,   2,   1,  78,   0,   1,   2,   9,   8,   7,   1,
         76,  88]])