In [2]:
import numpy as np

In [13]:
n = np.array([1,2,3],dtype='int16')
print (n)

[1 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
#Get Dimention
b.ndim

2

In [6]:
#Get Shape
b.shape

(2, 3)

In [14]:
#Get Type
n.dtype

dtype('int16')

In [20]:
#get size in bytes
b.itemsize

4

In [23]:
#get total size
b.size*b.itemsize #or  size gives total number of items
b.nbytes

24